development:
  db:
    host: 0.0.0.0
    database: pictie_development
  storage: './db'
  key: 'holyshit'
  # key: 'go0ddaytodie'
staging:
  db:
    host: 0.0.0.0
    database: pictie
  storage: './db/pictures'
  key: 'holyshit'
